### ISSUE TITLE
Scroll to Page ddoesn't trigger animation

### ISSUE THREAD

**Issue by Secretmapper** [n4kz/react-native-pages#10]
![ezgif-3-9fcb3dec8d](https://user-images.githubusercontent.com/4077143/27849110-0866bbf4-617d-11e7-956a-4dc0400a3f25.gif)

When using `scrollToPage`, animation (Animated, interpolate) does not work.

It's not clear in the gif above, but the first two instances (where the text 'Amount' animates from bottom to up) of page switch, it is done by swiping right and has an animation

On the second two instances, the page switch was done with `scrollToPage` and it doesn't trigger the animation

**Comment by n4kz** [comment]
Thanks for reporting! Unintentionally broke this in #9. Now fixed in released in `0.5.3`.
