### ISSUE TITLE
Indicators not changing on Android

### ISSUE THREAD

**Issue by jacobhummel** [n4kz/react-native-pages#17]
Indicators don't function correctly on Android. I'm on version `0.6.1`, using React Native `0.50.3`

[https://media.giphy.com/media/xT1R9ZzOF5svFd2DNC/giphy.gif](https://media.giphy.com/media/xT1R9ZzOF5svFd2DNC/giphy.gif)

**Comment by jacobhummel** [comment]
This may be related to [https://github.com/facebook/react-native/issues/16522](https://github.com/facebook/react-native/issues/16522) ?

**Comment by n4kz** [comment]
Thanks for reporting! I've just updated example to RN `0.50.3` and it still works for me in emulator on API 23 and API 26, in horizontal and vertical layout. Could you please provide more details or minimal code sample?

**Comment by n4kz** [comment]
Well, just caught it. For some reason no crash happens if second `Pages` component is present. Tested on RN `0.51.0-rc.2` and it works as expected in both cases.

I would suggest upgrading RN in your project to rc version now or to stable one as it gets released.
