### ISSUE TITLE
unsupported top level event "topScroll" dispatched

### ISSUE THREAD

**Issue by anhdbknws** [n4kz/react-native-pages#18]
hi guy.
i have an question. when i try to use "react-native-pages" in my project (react-native 0.50) i see a bug "unsupported top level event "topScroll" dispatched".
pls help me check this is bug from "react-native-pages" or from facebook?

and how can i fix it?

thanks

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. This error was fixed in RN starting from `0.50.4`. For more details please take a look at facebook/react-native#16522.
