### ISSUE TITLE
How to custom indicator style?

### ISSUE THREAD

**Issue by Peeratatt** [n4kz/react-native-pages#20]
I wanna custom indicator style to bar style.

**Comment by JackHowa** [comment]
does any one have ideas for how to do this for React Navigation?

**Comment by gldev** [comment]
Have you tried imporing the Indicator component from the package and reimplement it? You can pass a style like that, and even wrap it in a safeview.

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. To customize indicator position and appearance you can override `renderPager` prop on `Pages` as described in [readme](https://github.com/n4kz/react-native-pages#replacing-page-indicator). I've updated readme and listed all props passed to `renderPager` callback.

**Comment by eriegz** [comment]
@n4kz How about someone who wants to keep the indicator exactly as it is, but simply alter its style a bit? E.g.: something like what you could achieve by modifying `src/components/indicator/styles.js`, line 7:
```
4. container: {
5.   flex: 1,
6.   justifyContent: 'center',
7.   margin: 50,  <-------------------
8. },
```
Any tips for this?
