### ISSUE TITLE
Android (Indicator not tally)

### ISSUE THREAD

**Issue by nzrin** [n4kz/react-native-pages#23]
It seems indicator on android not tally when I tried to swipe left or right.

**Comment by supr-d** [comment]
I have the same issue on Android (react-native-pages@0.7.0). Also, the transition from one screen to another is too abrupt.

**Comment by supr-d** [comment]
Here it is:
![react-native-pages](https://user-images.githubusercontent.com/1255409/37044314-2f0ef412-2174-11e8-8fd1-2aa61812c4b5.gif)
Sometimes you can see abrupt animation when switching from green square to blue. On the real device this happens more often.
A render method looks like this:
```javascript
render() {
    return (
        <View style={{ flex: 1 }}>
            <Pages containerStyle={{ backgroundColor: '#159eda' }}>
                {['red', 'green', 'blue'].map(color => this.renderPage(color))}
            </Pages>
            <ButtonBack />
        </View>
    );
}
```

**Comment by pyramid-ali** [comment]
I have the same issue

**Comment by nicolas-rohricht** [comment]
I was having the same problem.

After some tests, I discovered that to PageControll works well, our Content must be inside of a View with flex and background style property set.

In my example, I would like to render 3 pages. Te result is:

<Pages indicatorColor={'#a6a6a6'} startPage={0}>
  <View style={{ flex: 1, backgroundColor: 'transparent' }}>
    { RenderMyContent }
 </View>
<View style={{ flex: 1, backgroundColor: 'transparent' }}>
    { RenderMyContent }
 </View>
<View style={{ flex: 1, backgroundColor: 'transparent' }}>
    { RenderMyContent }
 </View>
</Pages>

Hope this can help you.

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Starting from `0.8.0` `backgroundColor` hack is not needed anymore, as I've added `collapsable: false` prop to all child components.
