### ISSUE TITLE
Getting slow visible pages on first load

### ISSUE THREAD

**Issue by phuhk** [n4kz/react-native-pages#28]
Hi there, thanks for making this libs. Please help me, I getting slow visible pages on first load. I just follow examples and then apply for my project. But on first enter to this Components, I getting the first pages is visbile have delay (about 1-2s). Am I wrong some where? Please let me know, thanks again,

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Please, check this with latest component release `0.8.0` and fresh RN. If the issue is still there let me know by reopening it or create a new one.
