### ISSUE TITLE
Cannot embed vertical scroll into a horizontal scroll

### ISSUE THREAD

**Issue by thedoubler** [n4kz/react-native-pages#31]
Hi, 

I have a horizontal scrollview with 3 pages and on the first page I want to have a vertical scroll view with 2 pages.
The error I get is attached:
 Do you know how to solve this?
![simulator screen shot - iphone 6 - 2018-10-11 at 17 48 46](https://user-images.githubusercontent.com/11870889/46812828-35622d00-cd7e-11e8-9d88-58d1b1f951fa.png)

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. This was happening because outer `Pages` passes `progress` down to its children and inner `Pages` tries to use the same `Animated.Value`. To solve this please wrap inner `Pages` component within a `<View />`.
