### ISSUE TITLE
How to use isDragging?

### ISSUE THREAD

**Issue by jgutierrez11** [n4kz/react-native-pages#34]
I cannot find the way to implement this function, I need to detect if the user is dragging the pager

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. You can call `isDragging()` on a reference to `Pages` component. Please consider the following code:

```javascript
pagesRef = React.createRef();

onSomeEvent() {
  if (this.pagesRef.current.isDragging()) {
    /* do something */
  }
}

render() {
  return (
    <Pages ref={this.pagesRef} />
  );
}
