### ISSUE TITLE
Poor performance on Android

### ISSUE THREAD

**Issue by infaz** [n4kz/react-native-pages#35]
On iOS working fine. On Android when slides it slides all over the pages and comes to end of the page.

**Comment by kashifghaffarasim** [comment]
@infaz Yes same issues come again and again. Any idea how to resolve this?

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Please, check this with latest component release `0.8.0` and fresh RN. If the issue is still there let me know by reopening it or creating a new one.
