### ISSUE TITLE
Android choppy/slow performance

### ISSUE THREAD

**Issue by davebro** [n4kz/react-native-pages#4]
Just curious, is there a reason performance is so choppy/slow on Android? Are there considerations to be aware of with Android? I even have JS Dev Mode turned off in the Dev Settings, and it's still almost unusable. iOS is buttery smooth btw.

**Comment by n4kz** [comment]
I can confirm that android emulator and even devices have very poor performance in debug builds, but in my use case performance is acceptable in release builds. For this moment I see no possible improvements here, as all obvious things (like using pure components) are already done. I've tried to use native driver, but got stucked on complex animations.

**Comment by davebro** [comment]
Np, great job btw! Super nice on iOS, really like the animations you put in there.
