### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by j1mbl3s** [n4kz/react-native-pages#41]
Warning when using React Native 0.60.5:
> Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

**Comment by j1mbl3s** [comment]
Using `componentDidUpdate(...)` may be a better solution than `static getDerivedStateFromProps(...)`.

**Comment by n4kz** [comment]
Thanks for issue! Fixed this warning in `0.8.0`.
