### ISSUE TITLE
Vertical scroll in horizontal slider

### ISSUE THREAD

**Issue by oky1** [n4kz/react-native-pages#5]
Thanks. Nice lib. But...
Problems with vertical scroll in horizontal slider.
For example I want to put inside WebView component.
Vertical slider with images so slow.... almost not work. (Доделай плиз...и будет OK)

Android device 4.2.

**Comment by n4kz** [comment]
Thanks for reporting, looks like there is no easy way to support nested scroll views in RN at this moment. More on this facebook/react-native#8024 and facebook/react-native#2967. Android performance problems (in dev mode) described in n4kz/react-native-pages#4.
